/**
 * Curated demo SKUs (PubChem CIDs for 2D images & property cross-check via PUG REST).
 * See scripts/fetch-pubchem-props.mjs — https://pubchem.ncbi.nlm.nih.gov/docs/pug-rest
 */
import type { CatalogProduct } from "@/lib/types";

const img = (cid: string) =>
  `https://pubchem.ncbi.nlm.nih.gov/rest/pug/compound/cid/${cid}/PNG?record_type=2d&image_size=400x400`;

export const demoCatalog: CatalogProduct[] = [
  {
    id: "p01",
    slug: "benzalkonium-chloride-mm0224",
    title: "Benzalkonium chloride",
    brand: "Mikromol",
    cas_primary: "8001-54-5",
    catalog_code: "MM0224.00",
    description: "Quaternary ammonium antimicrobial; excipient and intermediate with documented impurity profile.",
    product_type: "Excipient; API intermediate; Impurity",
    api_family: "Benzalkonium chlorides",
    product_format: "Neat",
    promotion: false,
    promotion_tags: ["new"],
    fulfillment_city: "Hyderabad",
    fulfillment_state: "Telangana",
    moq_display: "500 mg · RFQ bulk",
    price_per_kg: null,
    min_order_kg: 0.0005,
    image_url: img("8753"),
    purity_grade: "Ph. Eur.",
    accreditation_product: "ISO 17034",
    accreditation_lab: "ISO 17025",
    analyte: "Benzalkonium chloride",
    impurity_type: "Intermediate",
    sil_type: "—",
    matrix: "Neat solid",
    category_slugs: ["crm", "media"],
  },
  {
    id: "p02",
    slug: "sodium-hydroxide-flakes",
    title: "Sodium hydroxide flakes",
    brand: "ELRASA",
    cas_primary: "1310-73-2",
    catalog_code: "ELR-CSF-25",
    description: "Pharma-grade caustic soda flakes for media preparation and process chemistry.",
    product_type: "Industrial alkali; Excipient",
    api_family: "Sodium hydroxide",
    product_format: "Flakes",
    promotion: true,
    promotion_tags: ["special_offer"],
    fulfillment_city: "Mumbai",
    fulfillment_state: "Maharashtra",
    moq_display: "25 kg drum",
    price_per_kg: 50,
    min_order_kg: 25,
    image_url: img("14798"),
    purity_grade: "≥ 98 %",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Sodium hydroxide",
    impurity_type: "By-product",
    sil_type: "—",
    matrix: "Solid flakes",
    category_slugs: ["solvents", "media"],
  },
  {
    id: "p03",
    slug: "acetonitrile-hplc",
    title: "Acetonitrile HPLC grade",
    brand: "ChromLab",
    cas_primary: "75-05-8",
    catalog_code: "CH3CN-HPLC-4L",
    description: "Ultra-low UV absorbance ACN for LC-MS and HPLC; 0.2 µm filtered.",
    product_type: "Chromatography solvent",
    api_family: "Nitriles",
    product_format: "Liquid",
    promotion: false,
    promotion_tags: [],
    fulfillment_city: "Hyderabad",
    fulfillment_state: "Telangana",
    moq_display: "4 L bottle",
    price_per_kg: null,
    min_order_kg: 4,
    image_url: img("6344"),
    purity_grade: "HPLC",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Acetonitrile",
    impurity_type: "Degradation product",
    sil_type: "—",
    matrix: "Single solution",
    category_slugs: ["solvents"],
  },
  {
    id: "p04",
    slug: "paracetamol-crm",
    title: "Paracetamol certified reference material",
    brand: "TraceCal",
    cas_primary: "103-90-2",
    catalog_code: "CRM-PARA-100MG",
    description: "Traceable CRM for HPLC and titrimetric assays; CoA with uncertainty budget.",
    product_type: "Certified reference material; API",
    api_family: "Anilides",
    product_format: "Neat",
    promotion: false,
    promotion_tags: ["new"],
    fulfillment_city: "Bengaluru",
    fulfillment_state: "Karnataka",
    moq_display: "100 mg ampoule",
    price_per_kg: null,
    min_order_kg: 0.0001,
    image_url: img("1983"),
    purity_grade: "99.8 ± 0.1 %",
    accreditation_product: "ISO 17034",
    accreditation_lab: "ISO 17025",
    analyte: "Paracetamol",
    impurity_type: "—",
    sil_type: "13C-labelled available (RFQ)",
    matrix: "Neat",
    category_slugs: ["crm"],
  },
  {
    id: "p05",
    slug: "ibuprofen-ph-eur",
    title: "Ibuprofen Ph. Eur.",
    brand: "SynthChem IN",
    cas_primary: "15687-27-1",
    catalog_code: "IBU-25KG",
    description: "Non-steroidal anti-inflammatory API; GMP documentation package.",
    product_type: "API",
    api_family: "Propionic acids",
    product_format: "Neat",
    promotion: true,
    promotion_tags: ["special_offer", "replacement_part"],
    fulfillment_city: "Ahmedabad",
    fulfillment_state: "Gujarat",
    moq_display: "25 kg",
    price_per_kg: 1200,
    min_order_kg: 25,
    image_url: img("3672"),
    purity_grade: "Ph. Eur.",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Ibuprofen",
    impurity_type: "Intermediate",
    sil_type: "—",
    matrix: "Neat powder",
    category_slugs: ["crm"],
  },
  {
    id: "p06",
    slug: "metformin-hcl",
    title: "Metformin hydrochloride",
    brand: "APIOne",
    cas_primary: "1115-70-4",
    catalog_code: "MET-HCL-5KG",
    description: "Biguanide antidiabetic API; micronized grade on request.",
    product_type: "API; Excipient",
    api_family: "Biguanides",
    product_format: "Neat",
    promotion: false,
    promotion_tags: [],
    fulfillment_city: "Hyderabad",
    fulfillment_state: "Telangana",
    moq_display: "5 kg",
    price_per_kg: 800,
    min_order_kg: 5,
    image_url: img("4091"),
    purity_grade: "USP / EP",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Metformin",
    impurity_type: "Degradation product; Intermediate",
    sil_type: "—",
    matrix: "Crystalline",
    category_slugs: ["media"],
  },
  {
    id: "p07",
    slug: "ethanol-absolute",
    title: "Ethanol absolute 99.9 %",
    brand: "ReagLab",
    cas_primary: "64-17-5",
    catalog_code: "ETOH-ABS-2.5L",
    description: "Absolute ethanol for extraction and chromatography; low water specification.",
    product_type: "Solvent",
    api_family: "Alcohols",
    product_format: "Liquid",
    promotion: false,
    promotion_tags: ["replacement_part"],
    fulfillment_city: "Pune",
    fulfillment_state: "Maharashtra",
    moq_display: "2.5 L",
    price_per_kg: null,
    min_order_kg: 2,
    image_url: img("702"),
    purity_grade: "AR",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Ethanol",
    impurity_type: "—",
    sil_type: "—",
    matrix: "Single solution",
    category_slugs: ["solvents"],
  },
  {
    id: "p08",
    slug: "methanol-lc-ms",
    title: "Methanol LC-MS grade",
    brand: "ChromLab",
    cas_primary: "67-56-1",
    catalog_code: "MeOH-LCMS-1L",
    description: "Low PPB background methanol for high-sensitivity LC-MS.",
    product_type: "Chromatography solvent",
    api_family: "Alcohols",
    product_format: "Liquid",
    promotion: false,
    promotion_tags: [],
    fulfillment_city: "Hyderabad",
    fulfillment_state: "Telangana",
    moq_display: "1 L",
    price_per_kg: null,
    min_order_kg: 1,
    image_url: img("887"),
    purity_grade: "LC-MS",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Methanol",
    impurity_type: "Degradation product",
    sil_type: "—",
    matrix: "Single solution",
    category_slugs: ["solvents"],
  },
  {
    id: "p09",
    slug: "dmso-anhydrous",
    title: "DMSO anhydrous",
    brand: "ReagLab",
    cas_primary: "67-68-5",
    catalog_code: "DMSO-500ML",
    description: "Molecular biology grade dimethyl sulfoxide; low water.",
    product_type: "Solvent; Excipient",
    api_family: "Sulfoxides",
    product_format: "Liquid",
    promotion: false,
    promotion_tags: ["new"],
    fulfillment_city: "Chennai",
    fulfillment_state: "Tamil Nadu",
    moq_display: "500 mL",
    price_per_kg: null,
    min_order_kg: 0.5,
    image_url: img("679"),
    purity_grade: "≥ 99.9 %",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Dimethyl sulfoxide",
    impurity_type: "—",
    sil_type: "—",
    matrix: "Single solution",
    category_slugs: ["solvents", "cells"],
  },
  {
    id: "p10",
    slug: "sodium-chloride-bp",
    title: "Sodium chloride BP",
    brand: "BioSalts",
    cas_primary: "7647-14-5",
    catalog_code: "NaCl-10KG",
    description: "Injectable-grade sodium chloride for buffers and media osmolarity adjustment.",
    product_type: "Excipient; Culture media component",
    api_family: "Alkali halides",
    product_format: "Neat",
    promotion: false,
    promotion_tags: [],
    fulfillment_city: "Mumbai",
    fulfillment_state: "Maharashtra",
    moq_display: "10 kg",
    price_per_kg: 2.5,
    min_order_kg: 10,
    image_url: img("5234"),
    purity_grade: "BP / EP",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Chloride",
    impurity_type: "By-product",
    sil_type: "—",
    matrix: "Aqueous buffer component",
    category_slugs: ["media"],
  },
  {
    id: "p11",
    slug: "glucose-anhydrous",
    title: "D-Glucose anhydrous",
    brand: "BioSalts",
    cas_primary: "50-99-7",
    catalog_code: "GLC-5KG",
    description: "Carbon source for fermentation and mammalian cell culture media.",
    product_type: "Culture media component; Excipient",
    api_family: "Carbohydrates",
    product_format: "Neat",
    promotion: true,
    promotion_tags: ["special_offer"],
    fulfillment_city: "Hyderabad",
    fulfillment_state: "Telangana",
    moq_display: "5 kg",
    price_per_kg: 4,
    min_order_kg: 5,
    image_url: img("5793"),
    purity_grade: "Cell culture",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Glucose",
    impurity_type: "Intermediate",
    sil_type: "13C6 glucose (RFQ)",
    matrix: "Powder",
    category_slugs: ["media", "cells"],
  },
  {
    id: "p12",
    slug: "tryptone-bacteriological",
    title: "Tryptone bacteriological",
    brand: "MediaPro",
    cas_primary: "—",
    catalog_code: "TRY-500G",
    description: "Pancreatic digest of casein for LB and nutrient broth formulations.",
    product_type: "Culture media component",
    api_family: "Peptones",
    product_format: "Neat",
    promotion: false,
    promotion_tags: [],
    fulfillment_city: "Bengaluru",
    fulfillment_state: "Karnataka",
    moq_display: "500 g",
    price_per_kg: 18,
    min_order_kg: 0.5,
    image_url: img("6305"),
    purity_grade: "Microbiology",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Total nitrogen",
    impurity_type: "—",
    sil_type: "—",
    matrix: "Dry powder",
    category_slugs: ["media"],
  },
  {
    id: "p13",
    slug: "citric-acid-anhydrous",
    title: "Citric acid anhydrous",
    brand: "AcidChem",
    cas_primary: "77-92-9",
    catalog_code: "CIT-25KG",
    description: "pH adjustment and chelation in formulations and buffers.",
    product_type: "Excipient",
    api_family: "Organic acids",
    product_format: "Neat",
    promotion: false,
    promotion_tags: [],
    fulfillment_city: "Delhi",
    fulfillment_state: "Delhi",
    moq_display: "25 kg",
    price_per_kg: 1.2,
    min_order_kg: 25,
    image_url: img("311"),
    purity_grade: "USP",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Citric acid",
    impurity_type: "Degradation product; By-product",
    sil_type: "—",
    matrix: "Crystalline",
    category_slugs: ["media"],
  },
  {
    id: "p14",
    slug: "edta-disodium-dihydrate",
    title: "EDTA disodium dihydrate",
    brand: "ChelateX",
    cas_primary: "6381-92-6",
    catalog_code: "EDTA-5KG",
    description: "Chelating agent for buffers, mobile phases, and cleaning validation.",
    product_type: "Excipient",
    api_family: "Aminocarboxylates",
    product_format: "Neat",
    promotion: false,
    promotion_tags: ["replacement_part"],
    fulfillment_city: "Vadodara",
    fulfillment_state: "Gujarat",
    moq_display: "5 kg",
    price_per_kg: 6,
    min_order_kg: 5,
    image_url: img("6141"),
    purity_grade: "AR",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "EDTA",
    impurity_type: "Intermediate",
    sil_type: "—",
    matrix: "Powder",
    category_slugs: ["media", "filtration"],
  },
  {
    id: "p15",
    slug: "tween-20-polysorbate",
    title: "Polysorbate 20 (Tween 20)",
    brand: "SurfBio",
    cas_primary: "9005-64-5",
    catalog_code: "PS20-1L",
    description: "Non-ionic surfactant for protein formulations and viral vectors.",
    product_type: "Excipient; API component",
    api_family: "Polysorbates",
    product_format: "Liquid",
    promotion: false,
    promotion_tags: ["new"],
    fulfillment_city: "Hyderabad",
    fulfillment_state: "Telangana",
    moq_display: "1 L",
    price_per_kg: null,
    min_order_kg: 1,
    image_url: img("443401"),
    purity_grade: "NF / EP",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Polysorbate 20",
    impurity_type: "Mixture",
    sil_type: "—",
    matrix: "Aqueous miscible liquid",
    category_slugs: ["cells"],
  },
  {
    id: "p16",
    slug: "ficoll-paque-plus",
    title: "Ficoll-Paque PLUS density medium",
    brand: "CellSep",
    cas_primary: "—",
    catalog_code: "FIC-500ML",
    description: "Sterile density gradient for isolation of mononuclear cells.",
    product_type: "Cell separation medium",
    api_family: "Density media",
    product_format: "Liquid",
    promotion: true,
    promotion_tags: ["special_offer"],
    fulfillment_city: "Bengaluru",
    fulfillment_state: "Karnataka",
    moq_display: "500 mL bottle",
    price_per_kg: null,
    min_order_kg: 0.5,
    image_url: img("962"),
    purity_grade: "Sterile GMP",
    accreditation_product: "ISO 17034",
    accreditation_lab: "ISO 17025",
    analyte: "Lymphocyte separation",
    impurity_type: "Mixture",
    sil_type: "—",
    matrix: "Colloidal solution",
    category_slugs: ["cells"],
  },
  {
    id: "p17",
    slug: "ptfe-syringe-filter-013um",
    title: "PTFE syringe filter 13 mm 0.45 µm",
    brand: "FilterMax",
    cas_primary: "9002-84-0",
    catalog_code: "SF-PTFE-13-045",
    description: "Hydrophobic PTFE for aggressive solvents and venting applications.",
    product_type: "Syringe filter",
    api_family: "Membrane filtration",
    product_format: "Single solution",
    promotion: false,
    promotion_tags: [],
    fulfillment_city: "Mumbai",
    fulfillment_state: "Maharashtra",
    moq_display: "100 / pack",
    price_per_kg: null,
    min_order_kg: 0.01,
    image_url: img("62389"),
    purity_grade: "HPLC certified",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "—",
    impurity_type: "—",
    sil_type: "—",
    matrix: "PTFE membrane",
    category_slugs: ["filters", "filtration"],
  },
  {
    id: "p18",
    slug: "pes-bottle-top-02um",
    title: "PES bottle-top filter 0.2 µm 500 mL",
    brand: "FilterMax",
    cas_primary: "—",
    catalog_code: "BTF-PES-02-500",
    description: "Low protein-binding PES for sterile filtration of media and buffers.",
    product_type: "Microbial filtration",
    api_family: "Membrane filtration",
    product_format: "Mixture",
    promotion: false,
    promotion_tags: ["new", "replacement_part"],
    fulfillment_city: "Hyderabad",
    fulfillment_state: "Telangana",
    moq_display: "12 / case",
    price_per_kg: null,
    min_order_kg: 0.05,
    image_url: img("887"),
    purity_grade: "Sterile",
    accreditation_product: "—",
    accreditation_lab: "ISO 17025",
    analyte: "Bioburden reduction",
    impurity_type: "—",
    sil_type: "—",
    matrix: "PES membrane",
    category_slugs: ["filtration", "filters"],
  },
];
